name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy
    - name: Install deps
      run: sudo apt-get install libfontconfig1-dev
    - name: Run fmt
      run: cargo +nightly fmt --check
    - name: Clippy
      run: cargo clippy --all-targets
    - name: Run tests
      run: cargo test
